name: Deploy Docusaurus to AWS Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build Docusaurus site
      run: npm run build

    - name: Setup SSH and known hosts
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
        
        # Debug known_hosts
        echo "Known hosts file contents:"
        cat ~/.ssh/known_hosts
        
        # Start the ssh-agent and add the key
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa
        
        # Debug SSH connection
        ssh -o StrictHostKeyChecking=accept-new -T ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} || { echo "SSH connection failed"; exit 1; }

    - name: Deploy to server
      run: |
        sudo apt-get update
        sudo apt-get install -y rsync
        rsync -avz --delete ./build/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/opt/bitnami/apache/htdocs/ || { echo "rsync failed"; exit 1; }